### ISSUE TITLE
Actividad 9

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-team-lmn#1]
[Practica 9.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-de-proyecto-de-ra-team-lmn/files/15301343/Practica.9.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
